export const ACTIVATION_CODE_REPOSITORY_INTERFACE = Symbol(
  'ACTIVATION_CODE_REPOSITORY_INTERFACE',
);

export const AUTH_SESSION_REPOSITORY_INTERFACE = Symbol(
  'AUTH_SESSION_REPOSITORY_INTERFACE',
);

export const SIGN_UP_USE_CASE_INTERFACE = Symbol('SIGN_UP_USE_CASE_INTERFACE');

export const SIGN_IN_USE_CASE_INTERFACE = Symbol('SIGN_IN_USE_CASE_INTERFACE');

export const GET_ME_USE_CASE_INTERFACE = Symbol('GET_ME_USE_CASE_INTERFACE');

export const UPDATE_ME_USE_CASE_INTERFACE = Symbol(
  'UPDATE_ME_USE_CASE_INTERFACE',
);

export const CREATE_ACTIVATION_CODE_USE_CASE_INTERFACE = Symbol(
  'CREATE_ACTIVATION_CODE_USE_CASE_INTERFACE',
);

export const ACTIVATE_ACCOUNT_USE_CASE_INTERFACE = Symbol(
  'ACTIVATE_ACCOUNT_USE_CASE_INTERFACE',
);

export const REFRESH_USE_CASE_INTERFACE = Symbol('REFRESH_USE_CASE_INTERFACE');

export const SIGN_OUT_USE_CASE_INTERFACE = Symbol(
  'SIGN_OUT_USE_CASE_INTERFACE',
);

export const HASH_SERVICE = Symbol('HASH_SERVICE');
