export const MATCH_REPOSITORY_INTERFACE = Symbol('MATCH_REPOSITORY_INTERFACE');

export const LIST_MATCH_USE_CASE_INTERFACE = Symbol(
  'LIST_MATCH_USE_CASE_INTERFACE',
);

export const CREATE_MATCH_USE_CASE_INTERFACE = Symbol(
  'CREATE_MATCH_USE_CASE_INTERFACE',
);

export const READ_MATCH_USE_CASE_INTERFACE = Symbol(
  'READ_MATCH_USE_CASE_INTERFACE',
);

export const UPDATE_MATCH_USE_CASE_INTERFACE = Symbol(
  'UPDATE_MATCH_USE_CASE_INTERFACE',
);

export const DELETE_MATCH_USE_CASE_INTERFACE = Symbol(
  'DELETE_MATCH_USE_CASE_INTERFACE',
);
