export const TEAM_REPOSITORY_INTERFACE = Symbol('TEAM_REPOSITORY_INTERFACE');

export const LIST_TEAM_USE_CASE_INTERFACE = Symbol(
  'LIST_TEAM_USE_CASE_INTERFACE',
);
export const CREATE_TEAM_USE_CASE_INTERFACE = Symbol(
  'CREATE_TEAM_USE_CASE_INTERFACE',
);
export const READ_TEAM_USE_CASE_INTERFACE = Symbol(
  'READ_TEAM_USE_CASE_INTERFACE',
);
export const UPDATE_TEAM_USE_CASE_INTERFACE = Symbol(
  'UPDATE_TEAM_USE_CASE_INTERFACE',
);
export const DELETE_TEAM_USE_CASE_INTERFACE = Symbol(
  'DELETE_TEAM_USE_CASE_INTERFACE',
);
