export const STADIUM_REPOSITORY_INTERFACE = Symbol(
  'STADIUM_REPOSITORY_INTERFACE',
);

export const LIST_STADIUM_USE_CASE_INTERFACE = Symbol(
  'LIST_STADIUM_USE_CASE_INTERFACE',
);

export const CREATE_STADIUM_USE_CASE_INTERFACE = Symbol(
  'CREATE_STADIUM_USE_CASE_INTERFACE',
);

export const READ_STADIUM_USE_CASE_INTERFACE = Symbol(
  'READ_STADIUM_USE_CASE_INTERFACE',
);

export const UPDATE_STADIUM_USE_CASE_INTERFACE = Symbol(
  'UPDATE_STADIUM_USE_CASE_INTERFACE',
);

export const DELETE_STADIUM_USE_CASE_INTERFACE = Symbol(
  'DELETE_STADIUM_USE_CASE_INTERFACE',
);
