export const USER_REPOSITORY_INTERFACE = Symbol('USER_REPOSITORY_INTERFACE');

export const LIST_USER_USE_CASE_INTERFACE = Symbol(
  'LIST_USER_USE_CASE_INTERFACE',
);

export const CREATE_USER_USE_CASE_INTERFACE = Symbol(
  'CREATE_USER_USE_CASE_INTERFACE',
);

export const READ_USER_USE_CASE_INTERFACE = Symbol(
  'READ_USER_USE_CASE_INTERFACE',
);

export const UPDATE_USER_USE_CASE_INTERFACE = Symbol(
  'UPDATE_USER_USE_CASE_INTERFACE',
);

export const DELETE_USER_USE_CASE_INTERFACE = Symbol(
  'DELETE_USER_USE_CASE_INTERFACE',
);
