export const GUESS_REPOSITORY_INTERFACE = Symbol('GUESS_REPOSITORY_INTERFACE');

export const LIST_GUESS_USE_CASE_INTERFACE = Symbol(
  'LIST_GUESS_USE_CASE_INTERFACE',
);

export const CREATE_GUESS_USE_CASE_INTERFACE = Symbol(
  'CREATE_GUESS_USE_CASE_INTERFACE',
);

export const READ_GUESS_USE_CASE_INTERFACE = Symbol(
  'READ_GUESS_USE_CASE_INTERFACE',
);

export const LIST_MY_GUESS_USE_CASE_INTERFACE = Symbol(
  'LIST_MY_GUESS_USE_CASE_INTERFACE',
);

export const LIST_GUESS_BY_MATCH_USE_CASE_INTERFACE = Symbol(
  'LIST_GUESS_BY_MATCH_USE_CASE_INTERFACE',
);

export const UPDATE_GUESS_USE_CASE_INTERFACE = Symbol(
  'UPDATE_GUESS_USE_CASE_INTERFACE',
);

export const DELETE_GUESS_USE_CASE_INTERFACE = Symbol(
  'DELETE_GUESS_USE_CASE_INTERFACE',
);

export const CALCULATE_GUESS_POINTS_USE_CASE_INTERFACE = Symbol(
  'CALCULATE_GUESS_POINTS_USE_CASE_INTERFACE',
);
